name: btc-env
channels:
  - defaults
dependencies:
  - python=3.9
  - python-graphviz
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - streamlit==1.50.0
    - torch==2.5.1
    - numpy==1.26.4
    - pandas==2.2.3
    - plotly==5.24.1
    - scikit-learn
    - matplotlib==3.7.5
    - seaborn==0.13.2
    - timeshap==1.0.4
    - openai==2.15.0
    - altair==4.2.2
    - yfinance>=0.2.40
    - shap==0.41.0
    - graphviz
    - requests
    - fredapi       # [추가] FRED 경제 데이터 API 라이브러리
